version: '3.8'
services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    platform: linux/amd64
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=weatherdb
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_USER=nieweglp
      - INFLUXDB_USER_PASSWORD=nieweglp

volumes:
  grafana-storage: {}
  influxdb-data:
    driver: local